apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexandria-ui
  labels:
    app: alexandria
    role: ui
spec:
  selector:
    matchLabels:
      app: alexandria
      role: ui
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: alexandria
        role: ui
    spec:
      containers:
        - name: alexandria-ui
          image: mkempster/alexandria-ui:1.0.4
          ports:
            - containerPort: 80

