apiVersion: v1
kind: Service
metadata:
  labels:
    name: alexandria-ui
  name: alexandria-ui
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: alexandria
    role: ui
